#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
Rscript Figure1.R "$@"

# The previous version of this file was commented-out and follows below:
#
# Rscript loaddependencies.R "$@"
# Rscript Figure1.R "$@"
# Rscript Figure2.R "$@"
# 
# 
# 
