# hash:sha256:96ab3584e58234ba64bb2159af4de470122850c9c7d66b524d9cc7553ad1fc8c
FROM registry.codeocean.com/codeocean/r-base:3.6.3-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN Rscript -e 'remotes::install_version("ggplot")'
